/*This file is generated by fileauto.sh used by test_suit.*/
/*Author: Mookel, all rights reversed.*/

#include <syslib.h>
#include "test_suit.h"

PRIVATE int test1()
{
    for(int i = 0; i <= 127; ++i) {
        char *pstr;
        char *tmp = sys_bin_to_ascii(i, 1);
        pstr = tmp;
        int  val = sys_esc(&tmp);
        printf("==>\n");
        printf("%d %s %d\n",i, pstr, val);

        tmp = sys_bin_to_ascii(i , 0);
        pstr = tmp;
        val = sys_esc(&tmp);
        printf("%d %s %d\n",i, pstr, val);

    }
    return 1;
}

PRIVATE int test2()
{
    int rval = 0;

    rval = sys_copyfile("dst.txt", "src.txt", "w");
    printf("rval = %d\n", rval);
    rval |= sys_copyfile("dst.txt", "src.txt", "a");
    printf("rval = %d\n", rval);
    //rval = sys_movefile("dst.txt", "src.txt", "a");
    printf("rval = %d\n", rval);

    return rval == FILE_ERR_NONE;
}

PRIVATE int test3()
{
    char target[128];
    int ret = com_concat(128, target, "first", "second", "last", NULL);
    printf("size = 128, concat : %s, ret = %d\n", target, ret);
    ret = com_concat(12, target, "first", "second", "last", NULL);
    printf("size = 12, concat : %s, ret = %d\n", target, ret);
    return 1;

}

PRIVATE int test4()
{
    char pathname[128];
    int rval = sys_searchenv("dst.txt", NULL, pathname);
    printf("%d, %s\n", rval, pathname);
    rval = sys_searchenv("clang", "PATH", pathname);
    printf("%d, %s\n", rval, pathname);

    return 1;
}

PRIVATE int test5()
{
    FILE *output = fopen("dst.txt", "w+");
    if(!output) {
        fprintf(stdout, "Open dst.txt failed.\n");
    }

    FILE *fp = sys_driver_1(output, 1, "src.txt");
    printf("addr of fp : %p\n", fp);

    return 1;

}

PRIVATE int test6()
{
    double x, m, dev;
    sys_mean(1, 0, &dev);
    for(x = 1.0; x <= 20.0; x++)
    {
        m = sys_mean(0, x, &dev);
        printf("mean of 1...%-10g = %-10g, dev = %-10g\n", x, m, dev);
    }

    return 1;
}

PRIVATE int test7()
{
    char *str1;
    char *str2;
    char *str3;
    char *str4;
    char *str5;
    char *str6;

    char *ptr1 = str1 = (char *)malloc(20);
    char *ptr2 = str2 = (char *)malloc(20);
    char *ptr3 = str3 = (char *)malloc(20);
    char *ptr4 = str4 = (char *)malloc(20);
    char *ptr5 = str5 = (char *)malloc(20);
    char *ptr6 = str6 = (char *)malloc(20);

    strcpy(str1, " 0x100c");
    strcpy(str2, "    100xx");
    strcpy(str3, "  033f");
    strcpy(str4, "-0x10f0z");
    strcpy(str5, " -100");
    strcpy(str6, "  -0033fd");

    char **p1, **p2;

    p1 = &str1;
    printf("%u\n", sys_stoul(p1));
    str1 = ptr1;
    p1 = &str1;
    printf("%d\n", sys_stol(p1));

    p1 = &str2;
    printf("%u\n", sys_stoul(p1));
    str2 = ptr2;
    p1 = &str2;
    printf("%d\n", sys_stol(p1));

    p1 = &str3;
    printf("%u\n", sys_stoul(p1));
    str3 = ptr3;
    p1 = &str3;
    printf("%d\n", sys_stol(p1));

    p1 = &str4;
    printf("%d\n", sys_stol(p1));

    p1 = &str5;
    printf("%d\n", sys_stol(p1));

    p1 = &str6;
    printf("%d\n", sys_stol(p1));


    free(ptr1);
    free(ptr2);
    free(ptr3);
    free(ptr4);
    free(ptr5);
    free(ptr6);

    return 1;

}


int __syslib_test__()
{
    int rval = 1;

    rval &= test1();
    //rval &= test2();
    rval &= test3();
    rval &= test4();
    //rval &= test5();
    rval &= test6();
    rval &= test7();

    return rval;
}
