/*This file is generated by fileauto.sh used by test_suit.*/
/*Author: Mookel, all rights reversed.*/

#include <stdio.h>
#include <set.h>
#include "test_suit.h"

int setcmp(SET_S **a, SET_S **b) { return set_compare(*a, *b); }

PRIVATE SET_S *s1, *s2, *s3, *s4;
PRIVATE SET_S *a[40];

PRIVATE void init()
{
    s1 = set_new();
    s2 = set_new();
    s3 = set_new();
    s4 = set_new();
}

PRIVATE void finish()
{
    set_del(s1);
    set_del(s2);
    set_del(s3);
    set_del(s4);

    int i = 0;
    for(;i < 40; ++i){
        if(a[i] != NULL) set_del(a[i]);
    }
}

PRIVATE int test1()
{
    int i = 0;

    SET_ADD(s2, 1024);
    SET_ADD(s2, 2047);

    //set_dump(s2);

    SET_REMOVE(s2, 1024);
    SET_REMOVE(s2, 2047);

    //set_dump(s2);

    //set_dump(s1);
    for (i = 0; i <= 1024; ++i) {
        SET_ADD(s1, i);
        if (!SET_TEST(s1, i) || !SET_MEMBER(s1, i)) {
            TEST_ASSERT_INT(0, 1); /*failed*/
        }
    }
    //set_dump(s1);
    for (i = 0; i <= 1024; ++i) {
        if (!SET_TEST(s1, i) || !SET_MEMBER(s1, i)) {
            TEST_ASSERT_INT(0, 1); /*failed*/
        }
    }

    for (i = 0; i <= 1024; ++i) {
        SET_REMOVE(s1, i);
        if (SET_TEST(s1, i) || SET_MEMBER(s1, i)) {
            TEST_ASSERT_INT(0, 1); /*failed.*/
        }
    }
    //set_dump(s1);

    for (i = 0; i <= 1024; ++i) {
        if (SET_TEST(s1, i) || SET_MEMBER(s1, i)) {
            TEST_ASSERT_INT(0, 1); /*failed.*/
        }
    }

    return 1;
}

PRIVATE int test2()
{
    set_truncate(s1);
    //set_dump(s1);
    TEST_ASSERT_LOGIC(SET_IS_EQUIV(s1, s2) == 1);

    SET_ADD(s1, 1);
    SET_ADD(s2, 1);
    SET_ADD(s3, 1);
    SET_ADD(s1, 517);
    SET_ADD(s2, 517);
    //set_dump(s1);
    //set_dump(s2);
    //set_dump(s3);

    //s1 {1, 517}
    //s2 {1, 517}
    //s3 {1}

    TEST_ASSERT_LOGIC(SET_IS_EQUIV(s1, s2));
    SET_REMOVE(s2, 517);
    //set_dump(s2);

    TEST_ASSERT_LOGIC(!SET_IS_EQUIV(s1, s2));
    TEST_ASSERT_LOGIC(!SET_IS_EQUIV(s2, s1));
    TEST_ASSERT_LOGIC(!SET_IS_EQUIV(s1, s3));
    TEST_ASSERT_LOGIC(SET_IS_EQUIV(s3, s2));
    TEST_ASSERT_LOGIC(SET_IS_EQUIV(s2, s3));
    //set_dump(s1);
    //set_dump(s2);
    //set_dump(s3);
    //s1 {1, 517}
    //s2 {1}
    //s3 {1}
    return 1;
}

PRIVATE int test3()
{
    SET_ADD(s1, 3);
    SET_ADD(s1, 6);
    SET_ADD(s1, 9);
    SET_ADD(s1, 12);
    SET_ADD(s1, 15);
    SET_ADD(s1, 16);
    SET_ADD(s1, 19);
    SET_ADD(s3, 18);

    //s1 {1, 3, 6, 9, 12, 15, 16, 19, 517}
    //s2 {1}
    //s3 {1, 18}
    //set_dump(s1);
    //set_dump(s2);
    //set_dump(s3);

    printf("s1 has %d elements\n", set_num_ele(s1));
    TEST_ASSERT_INT(set_num_ele(s1), 9);
    printf("s2 has %d elements\n", set_num_ele(s2));
    TEST_ASSERT_INT(set_num_ele(s2), 1);
    printf("s3 has %d elements\n", set_num_ele(s3));
    TEST_ASSERT_INT(set_num_ele(s3), 2);
    printf("s4 has %d elements\n", set_num_ele(s4));
    TEST_ASSERT_INT(set_num_ele(s4), 0);

    return 1;

}

PRIVATE int test4()
{
    /*first delete s2 then duplate.*/
    set_del(s2);
    s2 = set_dup(s1);
    TEST_ASSERT_LOGIC(SET_IS_EQUIV(s1, s2));
    //set_dump(s1);
    //set_dump(s2);

    TEST_ASSERT_LOGIC(!SET_IS_EMPTY(s1));
    TEST_ASSERT_LOGIC(!SET_IS_EMPTY(s2));
    TEST_ASSERT_LOGIC(!SET_IS_EMPTY(s3));
    TEST_ASSERT_LOGIC(SET_IS_EMPTY(s4));

    //set_dump(s1);
    //set_dump(s3);
    TEST_ASSERT_LOGIC(!SET_IS_DISJOINT(s1, s3));

    //set_dump(s1);
    //set_dump(s4);
    TEST_ASSERT_LOGIC(SET_IS_DISJOINT(s1, s4));

    //set_dump(s1);
    //set_dump(s3);
    TEST_ASSERT_LOGIC(SET_IS_INTERSECT(s1, s3));

    //set_dump(s1);
    //set_dump(s4);
    TEST_ASSERT_LOGIC(!SET_IS_INTERSECT(s1, s4));

    return 1;
}

PRIVATE int test5()
{
    set_dump(s1);
    set_dump(s2);
    set_dump(s3);
    set_dump(s4);

    //s1 : 1 3 6 9 12 15 16 19 517
    //s2 : 1 3 6 9 12 15 16 19 517
    //s3 : 1 18
    //s4 : empty

    TEST_ASSERT_LOGIC(set_subset(s1, s1));
    TEST_ASSERT_LOGIC(set_subset(s3, s3));
    TEST_ASSERT_LOGIC(set_subset(s4, s4));
    TEST_ASSERT_LOGIC(!set_subset(s3, s1));
    TEST_ASSERT_LOGIC(!set_subset(s4, s1));
    TEST_ASSERT_LOGIC(!set_subset(s1, s3));
    TEST_ASSERT_LOGIC(!set_subset(s4, s3));
    TEST_ASSERT_LOGIC(set_subset(s1, s4));
    TEST_ASSERT_LOGIC(set_subset(s3, s4));

    SET_ADD(s1, 18);
    //s1 : 1 3 6 9 12 15 16 18 19 517
    //s2 : 1 3 6 9 12 15 16 19 517
    //s3 : 1 18
    //s4 : empty

    TEST_ASSERT_LOGIC(set_subset(s1, s1));
    TEST_ASSERT_LOGIC(set_subset(s3, s3));
    TEST_ASSERT_LOGIC(!set_subset(s3, s1));
    TEST_ASSERT_LOGIC(set_subset(s1, s3));

    return 1;
}

PRIVATE int test6()
{

    puts("\ns2       =");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    puts("\ns3       =");
    set_print(s3, (fp_set_prnt) fprintf, stdout);
    SET_ASSIGN(s2, s3);
    puts("\ns2       =");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    puts("\ns1       =");
    set_print(s1, (fp_set_prnt) fprintf, stdout);
    SET_UNION(s2, s1);
    puts("\ns1 UNI s2=");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    SET_ASSIGN(s2, s3);
    puts("\ns2=");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    puts("\ns1=");
    set_print(s1, (fp_set_prnt) fprintf, stdout);
    SET_INTERSECT(s2, s1);
    puts("\ns1 INT s2=");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    SET_ASSIGN(s2, s3);
    puts("\ns2=");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    puts("\ns1=");
    set_print(s1, (fp_set_prnt) fprintf, stdout);
    SET_DIFFERENCE(s2, s1);
    puts("\ns1 DIF s2=");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    return 1;
}

PRIVATE int test7()
{

    set_truncate(s2);
    TEST_ASSERT_LOGIC(SET_IS_EMPTY(s2));

    printf("\ns2 before inverted = ");
    set_print(s2, (fp_set_prnt) fprintf, stdout);
    set_invert(s2);
    printf("\ns2 inverted = ");
    set_print(s2, (fp_set_prnt) fprintf, stdout);

    SET_CLEAR(s2);
    printf("\ns2 cleared  = ");
    set_print(s2, (fp_set_prnt) fprintf, stdout);

    SET_FILL(s2);
    printf("\ns2 filled   = ");
    set_print(s2, (fp_set_prnt) fprintf, stdout);

    return 1;
}

PRIVATE int test8()
{
    int i = 40;
    for(i = 40; --i >= 0;){
        a[i] = set_new();
        SET_ADD(a[i], i % 20);
    }

    SET_ADD(a[0], 418);
    SET_REMOVE(a[0], 418);
    SET_ADD(a[10], 418);
    SET_REMOVE(a[10], 418);

    printf("\nUnsorted:\n");
    for (i = 0; i < 40; i++) {
        printf("Set %d: ", i);
        set_print(a[i], (fp_set_prnt) fprintf, stdout);
        printf(i & 1 ? "\n" : "\t");
    }

    qsort(a, 40, sizeof(a[0]), setcmp);

    printf("\nSorted:\n");
    for (i = 0; i < 40; i++) {
        printf("Set %d: ", i);
        set_print(a[i], (fp_set_prnt) fprintf, stdout);
        printf(i & 1 ? "\n" : "\t");
    }

    return 1;
}

int __set_test__()
{
    int i;
    int rval = 1;

    init();

    rval &= test1();
    rval &= test2();
    rval &= test3();
    rval &= test4();
    rval &= test5();
    rval &= test6();
    rval &= test7();
    rval &= test8();

    finish();

    return rval;
}
