/*This file is generated by fileauto.sh used by test_suit.*/
/*Author: Mookel, all rights reversed.*/

#include "test_suit.h"
#include <stack.h>
#include <stdio.h>

#undef stack_err
#define stack_err(o) 0

int __stack_test__()
{
    stack_dcl(stk, int , 128);

    for (int i = 0; i < 128; i++) {
        push(stk, i);
        printf("size : %d\n", stack_ele(stk));
    }
    TEST_ASSERT_INT(stack_ele(stk), 128);
    TEST_ASSERT_INT(stack_full(stk), 1);

    popn(stk, 128);
    TEST_ASSERT_INT(stack_ele(stk), 0);
    TEST_ASSERT_INT(stack_empty(stk), 1);

    for(int i = 0;i < 128; i++) {
        push(stk, i);
    }
    for(int i = 0;i < 128; ++i){
        printf("pop value: %d\n", pop(stk));
    }
    TEST_ASSERT_INT(stack_empty(stk), 1);
    push(stk, 1);
    push(stk, 2);
    TEST_ASSERT_INT(stack_ele(stk), 2);
    stack_clear(stk);
    TEST_ASSERT_INT(stack_ele(stk), 0);

    return TEST_SUCCESS;
}

