/*This file is generated by fileauto.sh used by test_suit.*/
/*Author: Mookel, all rights reversed.*/

#include <syslib.h>
#include "test_suit.h"

PRIVATE int test1()
{
    for(int i = 0; i <= 127; ++i) {
        char *pstr;
        char *tmp = sys_bin_to_ascii(i, 1);
        pstr = tmp;
        int  val = sys_esc(&tmp);
        printf("==>\n");
        printf("%d %s %d\n",i, pstr, val);

        tmp = sys_bin_to_ascii(i , 0);
        pstr = tmp;
        val = sys_esc(&tmp);
        printf("%d %s %d\n",i, pstr, val);

    }
    return 1;
}

int __syslib_test__()
{
    int rval = 1;

    rval &= test1();

    return rval;
}
