/*This file is generated by fileauto.sh used by test_suit.*/
/*Author: Mookel, all rights reversed.*/

#include <yylib.h>
#include <compiler.h>
#include "test_suit.h"

int __yylib_test__()
{

    return 0;
}
