
/*---------------------------------------------*/

/*@A (C) 1992 Allen I. Holub                                                */

/*--------------------------------------------------------------
 *  Parser for llama-generated tables
 */

#include <stdio.h>
#include <string.h> 	  /* For strcat(), strlen() prototypes only.	   */
#include <stdlib.h>	      /* Needed only for prototype for exit(). Can be  */
			              /* discarded in most non-ANSI systems.	   */
#include <stdarg.h>
#include <l.h>

extern int	yylineno;     /* Supplied by LeX. */
extern int	yyleng;
extern char	*yytext;
extern int 	yylex();

void yy_code   (char *fmt, ...);
void yy_data   (char *fmt, ...);
void yy_bss    (char *fmt,...);
void yy_error  (char *fmt, ...);
void yy_comment(char *fmt, ...);
int  yy_next_token();



/*---------------------------------------------*/


#include <stdarg.h>
#include "acts.h"

#define CREATING_LLAMA_PARSER	/* Suppress various definitions in parser.h */
#include "parser.h"		        /* that conflict with llama-generated defs. */

/* This file is a llama input file that creates a parser for llama, like a snake
 * eating its tail. The resulting yyparse.c file can be used in place of the
 * recursive-descent parser in llpar.c. Note that, though this file is certainly
 * easier to write than the recursive-descent version, the resulting code is
 * about 1K larger. nows() should be called before firing up the parser.
 * Most of the external subroutines called from this module are in acts.c.
 * Exceptions are:
 */
extern char	*yytext;	/* Generated by lex	  */
extern int	yylineno;	/* Generated by lex	  */
extern void	nows(void);	/* Declared in llama.lex. */
extern void	ws(void);	/* Declared in llama.lex. */

#define YYSTYPE  char*	/* Value-stack type.	  */
